
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/header/navbar";
import { ThemeProvider } from "@/components/theme-provider";
import { ClerkProvider } from '@clerk/nextjs'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata: Metadata = {
  title: "ShortShots | Share Your Moments",
  description: "Create, upload and share short video moments with your audience. A modern platform for creators to express themselves through short-form video content.",
  keywords: "short videos, video sharing, content creation, social media, shorts platform",
  authors: [{ name: "Your Name" }],
  openGraph: {
    title: "ShortShots | Share Your Moments",
    description: "Create and share engaging short-form videos with your audience",
    images: [
      {
        url: '/og-image.png', // Replace with your actual OG image
        width: 1200,
        height: 630,
        alt: 'ShortShots Preview'
      }
    ],
    type: 'website'
  },
  twitter: {
    card: 'summary_large_image',
    title: "ShortShots | Share Your Moments",
    description: "Create and share engaging short-form videos with your audience"
  },
  viewport: 'width=device-width, initial-scale=1',
  themeColor: '#000000' // Adjust this to match your brand color
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          suppressHydrationWarning
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="container mx-auto">
              <Navbar />
              {children}
            </div>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}